apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: self-healing
  labels:
    app: self-healing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: self-healing
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
      
  template:
    metadata:
      labels:
         app: self-healing
    spec:
      containers:
       - name: self-healing
         image: eu.gcr.io/microservices-2020/self-healing:v1
         ports:
          - containerPort: 8080
         imagePullPolicy: Always
         args:
          - /bin/sh
          - -c
          - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
         livenessProbe:
           httpGet:
             path: /actuator/health/
             port: 8080
           initialDelaySeconds: 5
           periodSeconds: 5
         readinessProbe:
           httpGet:
             path: /actuator/health/
             port: 8080
           initialDelaySeconds: 5
           periodSeconds: 5
---      
apiVersion: v1
kind: Service
metadata:
  name: self-healing
  labels:
    name: self-healing
spec:
  selector:
    app: self-healing
  ports:
   - port: 8080
     targetPort: 8080
  type: LoadBalancer